import pandas as pd

# Data provided by the user
data = {
    "Blog Title": [
        "What Does Indoor Air Quality Have to Do With Allergies?",
        "AFUE Rating Franklin, TN",
        "Improve Your Home’s Indoor Air Quality",
        "Why Do I Need AC Maintenance Now?",
        "AC Maintenance Checklist",
        "Common AC Purchasing Mistakes to Avoid",
        "Ductless Air Conditioning Systems Nashville, TN",
        "3 Health Benefits for Using Your AC While Sleeping",
        "Why Is My AC Blowing Hot Air?",
        "4 Important Heat Pump Maintenance Tips",
        "Transitioning Your Heat Pump",
        "Signs I Need a New Furnace",
        "Heating Repair vs Replacement Spring Hill, TN",
        "Furnace Repair Spring Hill, TN",
        "HVAC Ice Buildup in Spring Hill, TN",
        "Heating Efficiency Tips Spring Hill, TN",
        "Spring Hill’s Heat Dilemma: Repair or Replace Your Unit",
        "HVAC Maintenance Spring Hill, TN",
        "Heating System Maintenance Spring Hill, TN",
        "Spring AC Maintenance",
        "Zone Control HVAC Systems",
        "Ductless AC Columbia, TN",
        "HVAC Tips Columbia, TN",
        "Energy Saving Tips Columbia, TN",
        "Fall for Heating and Cooling Upgrades",
        "Prep Your HVAC System for Cooler Weather",
        "Energy Saving Features in Your Heating System",
        "Affordable HVAC Services Columbia, TN",
        "HVAC Maintenance Columbia, TN",
        "Licensed HVAC Contractor / Choosing the Right HVAC System / HVAC Company Columbia",
    ],
    "Keywords": [
        [
            "indoor air quality and allergies",
            "how indoor air affects allergies",
            "IAQ allergy prevention tips",
            "reduce allergens in home air",
            "indoor allergen control USA",
            "improve indoor air for allergies",
            "allergens and air quality",
        ],
        [
            "AFUE rating meaning",
            "what is AFUE rating",
            "AFUE rating furnace efficiency",
            "AFUE efficiency chart",
            "AFUE rating Franklin TN",
            "90% AFUE meaning",
            "high AFUE furnace benefits",
        ],
        [
            "improve indoor air quality",
            "home IAQ improvement tips",
            "how to improve indoor air quality",
            "best air purifier for home",
            "reduce indoor pollution at home",
            "enhance home air quality USA",
            "whole-home air filtration system",
        ],
        [
            "why AC maintenance is important",
            "benefits of AC maintenance",
            "when to service AC",
            "AC tune-up importance",
            "AC maintenance timing",
            "prevent AC breakdown with maintenance",
            "cost of skipping AC maintenance",
        ],
        [
            "AC maintenance checklist",
            "air conditioner maintenance checklist",
            "HVAC maintenance checklist",
            "spring AC maintenance steps",
            "DIY AC maintenance guide",
            "seasonal AC checklist",
            "AC tune-up checklist",
        ],
        [
            "AC buying mistakes",
            "common mistakes buying air conditioner",
            "how to choose AC unit",
            "AC purchasing guide",
            "avoid AC purchase errors",
            "AC size selection mistakes",
            "HVAC purchase tips",
        ],
        [
            "ductless AC Nashville",
            "ductless air conditioner Nashville TN",
            "mini-split installation Nashville",
            "benefits of ductless AC systems",
            "ductless HVAC Nashville",
            "ductless AC service Nashville",
            "ductless cooling Nashville TN",
        ],
        [
            "health benefits of sleeping with AC",
            "is AC good for sleep health",
            "AC and better sleep",
            "air conditioning and sleep quality",
            "health benefits AC running at night",
            "AC reduces allergens during sleep",
            "sleep in cooled room benefits",
        ],
        [
            "AC blowing hot air causes",
            "why AC blows hot air",
            "fixes for hot air from AC",
            "AC heating problems solutions",
            "troubleshooting AC hot air",
            "AC cool air stopped",
            "air conditioner blowing warm air",
        ],
        [
            "heat pump maintenance tips",
            "heat pump tune-up checklist",
            "how to maintain heat pump",
            "heat pump service tips",
            "seasonal heat pump maintenance",
            "heat pump care guide",
            "prolong heat pump life",
        ],
        [
            "transition from AC to heat pump",
            "switching to heat pump system",
            "upgrade to heat pump HVAC",
            "heat pump replacement tips",
            "benefits of transitioning to heat pump",
            "switching heating to heat pump USA",
            "energy savings switching to heat pump",
        ],
        [
            "signs you need a new furnace",
            "when to replace furnace",
            "furnace replacement indicators",
            "furnace lifespan signs",
            "old furnace replacement guide",
            "how long does a furnace last",
            "furnace repair vs replace signs",
        ],
        [
            "heating repair vs replacement",
            "furnace repair vs replace Spring Hill TN",
            "HVAC repair or replace decision",
            "cost of furnace repair vs replacement",
            "heating replacement Spring Hill TN",
            "best option repair or replace heater",
            "Spring Hill TN heating contractor",
        ],
        [
            "furnace repair Spring Hill TN",
            "heating repair services Spring Hill",
            "emergency furnace repair Spring Hill TN",
            "affordable furnace repair TN",
            "furnace contractor Spring Hill TN",
            "HVAC heating repair Spring Hill",
            "best furnace repair near me Spring Hill TN",
        ],
        [
            "HVAC ice buildup causes",
            "frozen AC coil repair Spring Hill TN",
            "why HVAC unit is freezing up",
            "ice buildup on air conditioner",
            "HVAC freeze up troubleshooting",
            "AC coil frozen Spring Hill TN",
            "HVAC ice problem repair TN",
        ],
        [
            "heating efficiency tips",
            "how to make furnace more efficient",
            "improve heating system efficiency",
            "energy saving tips heating Spring Hill TN",
            "efficient furnace operation guide",
            "save money on heating Spring Hill TN",
            "heating efficiency upgrades TN",
        ],
        [
            "Spring Hill HVAC repair vs replace",
            "repair or replace AC Spring Hill TN",
            "furnace vs AC replacement dilemma",
            "cost to replace HVAC Spring Hill TN",
            "deciding HVAC repair or replacement",
            "HVAC unit replacement TN",
            "local HVAC contractors Spring Hill TN",
        ],
        [
            "HVAC maintenance Spring Hill TN",
            "heating and cooling tune-up Spring Hill",
            "annual HVAC maintenance Spring Hill",
            "AC and furnace service TN",
            "HVAC contractor Spring Hill TN",
            "emergency HVAC maintenance Spring Hill",
            "HVAC inspection Spring Hill TN",
        ],
        [
            "heating system maintenance Spring Hill TN",
            "furnace tune-up Spring Hill",
            "winter heating maintenance tips",
            "heating contractor Spring Hill TN",
            "annual heating service Spring Hill",
            "emergency heating repair Spring Hill TN",
            "preventative heating system maintenance",
        ],
        [
            "spring AC maintenance tips",
            "seasonal AC maintenance checklist",
            "prepare AC for summer",
            "spring HVAC tune-up",
            "AC service in spring season",
            "AC inspection before summer",
            "AC preventative maintenance spring",
        ],
        [
            "zone control HVAC systems",
            "what is HVAC zoning",
            "benefits of zone control HVAC",
            "multi-zone HVAC system cost",
            "HVAC zoning installation USA",
            "HVAC zone control advantages",
            "HVAC zoning system guide",
        ],
        [
            "ductless AC Columbia TN",
            "mini split installation Columbia TN",
            "ductless air conditioner service Columbia",
            "ductless HVAC Columbia TN",
            "ductless mini split contractor Columbia",
            "ductless AC repair Columbia TN",
            "best ductless AC Columbia TN",
        ],
        [
            "HVAC tips Columbia TN",
            "energy saving HVAC tips",
            "Columbia TN HVAC maintenance advice",
            "HVAC troubleshooting tips",
            "seasonal HVAC care Columbia TN",
            "best HVAC practices Columbia",
            "HVAC care tips for homeowners",
        ],
        [
            "energy saving tips Columbia TN",
            "how to save on energy bills HVAC",
            "home energy efficiency Columbia TN",
            "reduce heating and cooling costs",
            "save money HVAC energy tips",
            "energy efficient HVAC Columbia TN",
            "electricity saving tips Columbia",
        ],
        [
            "fall HVAC upgrades",
            "heating and cooling upgrades fall season",
            "best HVAC upgrades autumn",
            "fall HVAC maintenance tips",
            "seasonal heating and cooling upgrades",
            "upgrade HVAC system before winter",
            "fall home HVAC checklist",
        ],
        [
            "prepare HVAC for winter",
            "prepping heating system for cold weather",
            "fall HVAC preparation tips",
            "HVAC checklist before winter",
            "winterize HVAC system USA",
            "get HVAC ready for winter",
            "seasonal HVAC prep guide",
        ],
        [
            "energy saving features heating system",
            "efficient furnace features",
            "heating system upgrades for efficiency",
            "eco-friendly heating system options",
            "modern heating energy saving features",
            "HVAC technology for energy savings",
            "green heating system features",
        ],
        [
            "affordable HVAC Columbia TN",
            "HVAC services Columbia TN",
            "cheap HVAC repair Columbia TN",
            "affordable AC repair Columbia",
            "budget-friendly HVAC Columbia TN",
            "local HVAC service Columbia",
            "affordable furnace repair Columbia TN",
        ],
        [
            "HVAC maintenance Columbia TN",
            "annual HVAC service Columbia TN",
            "HVAC tune-up Columbia TN",
            "AC and heating service Columbia",
            "preventative HVAC maintenance Columbia",
            "HVAC contractor Columbia TN",
            "Columbia HVAC inspection services",
        ],
        [
            "licensed HVAC contractor Columbia TN",
            "why hire licensed HVAC contractor",
            "choosing the right HVAC system USA",
            "HVAC contractor Columbia TN reviews",
            "how to choose HVAC company Columbia TN",
            "best HVAC contractor Columbia TN",
            "tips for hiring HVAC contractor",
        ],
    ],
}

# Flatten the data for CSV format
rows = []
for i, title in enumerate(data["Blog Title"]):
    for keyword in data["Keywords"][i]:
        rows.append([title, keyword])

# Create DataFrame
df = pd.DataFrame(rows, columns=["Blog Title", "Keyword"])

# Save to CSV
file_path = "/mnt/data/blog_keywords.csv"
df.to_csv(file_path, index=False)

file_path
